<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent><groupId>io.backsmith</groupId><artifactId>backsmith-parent</artifactId><version>0.1.1</version></parent>
  <artifactId>backsmith-template-engine</artifactId>
  <dependencies>
    <dependency><groupId>com.github.spullara.mustache.java</groupId><artifactId>compiler</artifactId><version>0.9.14</version></dependency>
  </dependencies>
</project>
