<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent><groupId>io.backsmith</groupId><artifactId>backsmith-parent</artifactId><version>1.0.0</version></parent>
  <artifactId>backsmith-core</artifactId>
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
  </build>
  <dependencies>
    <dependency><groupId>io.backsmith</groupId><artifactId>backsmith-model</artifactId><version>${project.version}</version></dependency>
    <dependency><groupId>io.backsmith</groupId><artifactId>backsmith-template-engine</artifactId><version>${project.version}</version></dependency>
    <dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-databind</artifactId></dependency>
    <dependency><groupId>com.fasterxml.jackson.dataformat</groupId><artifactId>jackson-dataformat-yaml</artifactId></dependency>
    <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
  </dependencies>
</project>
